use std::env;
use std::ffi::OsStr;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=tests/fixtures/verify_cli");

    let mut generated = String::new();
    generated.push_str("// @generated by build.rs\n");

    for kind in ["pass", "fail"] {
        let dir = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests/fixtures/verify_cli")
            .join(kind);
        println!("cargo:rerun-if-changed={}", dir.display());

        let mut names = Vec::new();
        for entry in fs::read_dir(&dir).expect("read fixture dir") {
            let entry = entry.expect("fixture entry");
            let path = entry.path();
            println!("cargo:rerun-if-changed={}", path.display());
            if !entry.file_type().expect("fixture type").is_file() {
                continue;
            }
            if path.extension().and_then(OsStr::to_str) != Some("rs") {
                continue;
            }
            names.push(
                path.file_stem()
                    .and_then(OsStr::to_str)
                    .expect("fixture stem")
                    .to_owned(),
            );
        }
        names.sort();

        for name in names {
            let variant_name = if kind == "pass" { "Pass" } else { "Fail" };
            generated.push_str(&format!(
                r#"#[test]
fn verify_cli_{kind}_{name}() {{
    let output = run_fixture(FixtureKind::{variant_name}, {name:?});
    assert_cli_snapshot(FixtureKind::{variant_name}, {name:?}, &output);
}}

"#,
                kind = kind,
                name = name,
                variant_name = variant_name,
            ));
        }
    }

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("verify_cli_tests.rs"), generated).expect("write generated tests");
}
